const cartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  SET_FIREBASE_CART: 'SET_FIREBASE_CART',
  UPDATE_FIREBASE_CART: 'UPDATE_FIREBASE_CART',
};

export default cartActionTypes;
